//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendBO.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class EH_Person
    {
        public decimal PersonId { get; set; }
        public string PersonName { get; set; }
        public string PersonMailID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
