//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendDAL.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using BackendBO.BusinessObjects;
    
    public partial class EHContext : DbContext
    {
        public EHContext()
            : base("name=EHContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EH_Person> EH_Person { get; set; }
        public virtual DbSet<EH_PersonRoleMapping> EH_PersonRoleMapping { get; set; }
        public virtual DbSet<EH_Role> EH_Role { get; set; }
    }
}
